### ISSUE TITLE
Dataset running issue

### ISSUE THREAD

**Issue by zeyulong** [arclab-hku/ESVIO#1]
Thank you for your outstanding work.

I used the dataset in the GitHub repository [Event_based_VO-VIO-SLAM](https://github.com/arclab-hku/Event_based_VO-VIO-SLAM). When I run Dataset for Stereo EVIO, everything works fine. However, when I run Modified VECtor Dataset and Modified DSEC Dataset, the terminal interface always displays "Not enough features or parallax; Move device around", and cannot be initialized successfully. The rviz interface does not generate a trajectory . The attached picture is as follows:

```bash
# Modified VECtor Dataset
roslaunch esvio_estimator esvio_VECtor_small_scale.launch
rosbag play --clock -r 1.0 board_slow1.synced.merged.bag
```

<img width="1333" alt="2024-03-30_09-27" src="https://github.com/arclab-hku/ESVIO/assets/95930415/264d45de-4cdd-42ce-b660-96187692e118">

```bash
# Modified DSEC Dataset
roslaunch esvio_estimator esvio_DSEC.launch
rosbag play --clock -r 1.0 dsec_zurich_city_04_a.bag 
```

<img width="1367" alt="2024-03-30_09-33" src="https://github.com/arclab-hku/ESVIO/assets/95930415/14ef688b-b169-4b7e-b900-aa3b0b17c542">

Please tell me how should I solve this problem? Thank you again.

**Comment by cpymaple** [comment]
> Thank you for your outstanding work.
> 
> I used the dataset in the GitHub repository [Event_based_VO-VIO-SLAM](https://github.com/arclab-hku/Event_based_VO-VIO-SLAM). When I run Dataset for Stereo EVIO, everything works fine. However, when I run Modified VECtor Dataset and Modified DSEC Dataset, the terminal interface always displays "Not enough features or parallax; Move device around", and cannot be initialized successfully. The rviz interface does not generate a trajectory . The attached picture is as follows:
> 
> ```shell
> # Modified VECtor Dataset
> roslaunch esvio_estimator esvio_VECtor_small_scale.launch
> rosbag play --clock -r 1.0 board_slow1.synced.merged.bag
> ```
> 
> <img alt="2024-03-30_09-27" width="1333" src="https://private-user-images.githubusercontent.com/95930415/318158376-264d45de-4cdd-42ce-b660-96187692e118.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTYzOTMsIm5iZiI6MTcxMTk1NjA5MywicGF0aCI6Ii85NTkzMDQxNS8zMTgxNTgzNzYtMjY0ZDQ1ZGUtNGNkZC00MmNlLWI2NjAtOTYxODc2OTJlMTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA3MjEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NDljMWQ5NGZmZjJhMGQzNmVjNDIxMjA2Y2ZkOGU0OWUxZjE5NTIwNjY4MzM3MDZlNDA1Y2Q3Y2E0YmVhNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fF3qEaGwgu9DRl-hbFSbIWZU9tGymgAjiGadtV6Zzis">
> ```shell
> # Modified DSEC Dataset
> roslaunch esvio_estimator esvio_DSEC.launch
> rosbag play --clock -r 1.0 dsec_zurich_city_04_a.bag 
> ```
> 
> <img alt="2024-03-30_09-33" width="1367" src="https://private-user-images.githubusercontent.com/95930415/318158510-14ef688b-b169-4b7e-b900-aa3b0b17c542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTYzOTMsIm5iZiI6MTcxMTk1NjA5MywicGF0aCI6Ii85NTkzMDQxNS8zMTgxNTg1MTAtMTRlZjY4OGItYjE2OS00YjdlLWI5MDAtYWEzYjBiMTdjNTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA3MjEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NWFhYzYyZmQyZDg5MzRiYTBhMTZjN2QyN2ZmOTVlMTU0YTg5ODEyYWFhMDIyOWIzOTBlMmMxOTNlZDJmZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tDtk2jF9js_GbXkkmimX6mR2ZLbAy9rCKNCy8uPzsT8">
> Please tell me how should I solve this problem? Thank you again.

Hi, Thanks for your interest.

The inconsistency is due to incorrect extrinsic between the camera and IMU. In the HKU Dataset, we modified the read-in section of imu in "stereo_estimator_node.cpp" to modify the coordinate of the VIO for real flight.

To enable the operation of ESVIO under VECtor and DSEC datasets, there are two approaches:

1. You can modify the read-in section in stereo_estimator_node.cpp, switching from the normal version to the flight version (see in the codes).

2. Alternatively, adjust the extrinsic between the camera and IMU in the config file. For guidance on making the modification, please refer to the comments related to the flight version within the "esvio/esvio.yaml" file.

Hope this can solve your problems.

**Comment by zeyulong** [comment]
Thank you so much! Looking forward to seeing more outstanding work from you. (o^ ^o)
