### ISSUE TITLE
Other Dataset running issue

### ISSUE THREAD

**Issue by LaCampanela** [arclab-hku/ESVIO#3]
When I run the code on the DSEC and ECMD datasets, the code starts normally, but no trace appears in rviz, and the terminal keeps reporting the following issues, whether using ESIO or ESVIO.
![2024-05-23 20-20-22屏幕截图](https://github.com/arclab-hku/ESVIO/assets/133941230/f944bde8-7a7c-41b8-a76e-f571192cc4d7)
![a](https://github.com/arclab-hku/ESVIO/assets/133941230/a0936e44-faac-46b4-91db-639fb84b2242)

![2024-05-23 20-22-42屏幕截图](https://github.com/arclab-hku/ESVIO/assets/133941230/536b0cd5-a865-4336-b399-2115c86255b5)

![2024-05-23 20-22-59屏幕截图](https://github.com/arclab-hku/ESVIO/assets/133941230/1f9471e2-fa66-40d1-af6c-2020a389523e)

I have checked the camera's internal and external parameters corresponding to yaml files, and I can also run the HKUST dataset properly.

**Comment by LaCampanela** [comment]
![Uploading a.png…]()

**Comment by cpymaple** [comment]
Hi, the problem seems very similar to the following issue: https://github.com/arclab-hku/ESVIO/issues/1#issuecomment-2029300265. Maybe you can try the above method.

**Comment by LaCampanela** [comment]
I have tried both of the solutions mentioned in this issue, and I have confirmed that the external parameters of the IMU and camera in the yaml file are the same as in the official documentation, and I have tried using normal verion and flight ersion respectively, but both have this problem.

And I personally think that this error has nothing to do with IMU, it is a feature tracking problem.

**Comment by cpymaple** [comment]
> I have tried both of the solutions mentioned in this issue, and I have confirmed that the external parameters of the IMU and camera in the yaml file are the same as in the official documentation, and I have tried using normal verion and flight ersion respectively, but both have this problem.
> 
> And I personally think that this error has nothing to do with IMU, it is a feature tracking problem.

1. Do you try other datasets? Is the result normal? 
2. The terminal also shows "IMU excitation not enough" which may be the initialization problem. You can try to enable the ```// if(!result)  //    {result = initialStructure();}//mono part``` in estimator.cpp file.
3. For the DSEC dataset, you can refer to the following video link: https://www.bilibili.com/video/BV168411778U?p=41&vd_source=c4be0359ec60c90d434f634ab4075470

**Comment by LaCampanela** [comment]
I confirm that the code works properly on your own recorded data set with trajectory generation, but I still can't run the DSEC dataset properly after trying the method you mentioned. I also just tried testing on the VECtor dataset, and it also shows "Not enough features or parallax;  "Move device around" error.

Do you confirm that this version of the code can run the DSEC data set normally？

![b](https://github.com/arclab-hku/ESVIO/assets/133941230/3c876ef1-3633-472d-8b3f-180b3d85c8e8)

**Comment by cpymaple** [comment]
1. I confirm that the version can run on HKU datasets, MVSEC, DSEC, VECtor Datasets. I think you should try these datasets to test the algorithm for further evaluation.
2. You can try the following DSEC rosbag: https://github.com/arclab-hku/Event_based_VO-VIO-SLAM?tab=readme-ov-file#Modified-dsec-dataset. The problem you encounter may also related to the frequency of event streams. or the version of Ceres library.
3. In your terminal, I still think the problem you encounter may be due to the incorrect extrinsic between cam and imu.
4. I have already presented the video showing our algorithm can run in DSEC and VECtor datasets for reference.
